config/routes.rb
Switter2::Application.routes.draw do

 

  

resources :swits do
  resources :comments, :users, :sweets, :sours, :doortags
end
  devise_for :users

root :to => 'swits#index'

end

app/models/doortag.rb
class Doortag < ActiveRecord::Base
	belongs_to :swit
end

app/controllers/doortags_controller.rb
class DoortagsController < ApplicationController
  before_action :set_doortag, only: [:show, :edit, :update, :destroy]

  # GET /doortags
  # GET /doortags.json
  def index
    @doortags = Doortag.all
  end

  # GET /doortags/1
  # GET /doortags/1.json
  def show
  end

  # GET /doortags/new
  def new
    @doortag = Doortag.new
  end

  # GET /doortags/1/edit
  def edit
  end

  # POST /doortags
  # POST /doortags.json
  def create
    @doortag = Doortag.new(doortag_params)

    respond_to do |format|
      if @doortag.save
        format.html { redirect_to @doortag }
        format.json { render action: 'show', status: :created, location: @doortag }
      else
        format.html { render action: 'new' }
        format.json { render json: @doortag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doortags/1
  # PATCH/PUT /doortags/1.json
  def update
    respond_to do |format|
      if @doortag.update(doortag_params)
        format.html { redirect_to @doortag, notice: 'Doortag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @doortag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doortags/1
  # DELETE /doortags/1.json
  def destroy
    @doortag.destroy
    respond_to do |format|
      format.html { redirect_to doortags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doortag
      @doortag = Doortag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doortag_params
      params.require(:doortag).permit(:tag, :swit_id)
    end
end

app/helpers/doortags_helper.rb
module DoortagsHelper
end

app/views/doortags/_form.html.erb
<%= form_for(@doortag) do |f| %>
  <% if @doortag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doortag.errors.count, "error") %> prohibited this doortag from being saved:</h2>

      <ul>
      <% @doortag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>

  <div class="field">
    <%= f.label :swit_id %><br>
    <%= f.number_field :swit_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doortags/edit.html.erb
<h1>Editing doortag</h1>

<%= render 'form' %>

<%= link_to 'Show', @doortag %> |
<%= link_to 'Back', doortags_path %>

app/views/doortags/index.html.erb
<h1>Listing doortags</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>String</th>
      <th>Swit</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @doortags.each do |doortag| %>
      <tr>
        <td><%= doortag.tag %></td>
        
        <td><%= doortag.swit_id %></td>
        <td><%= link_to 'Show', doortag %></td>
        <td><%= link_to 'Edit', edit_doortag_path(doortag) %></td>
        <td><%= link_to 'Destroy', doortag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doortag', new_doortag_path %>

app/views/doortags/new.html.erb
<h1>New doortag</h1>

<%= render 'form' %>

<%= link_to 'Back', doortags_path %>

app/views/doortags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @doortag.tag %>
</p>


<p>
  <strong>Swit:</strong>
  <%= @doortag.swit_id %>
</p>

<%= link_to 'Edit', edit_doortag_path(@doortag) %> |
<%= link_to 'Back', doortags_path %>