config/routes.rb
Switter2::Application.routes.draw do

 

  

resources :swits do
  resources :comments, :users, :sweets, :sours, :doortags
end
  devise_for :users

root :to => 'swits#index'

end

app/models/swit.rb
class Swit < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :sweets
	has_many :sours
	has_many :doortags

	validates :post, :presence => true, :length => { :maximum => 140 }
end

app/controllers/swits_controller.rb
class SwitsController < ApplicationController
  before_action :set_swit, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!
 
  
  # GET /swits
  # GET /swits.json
  def index
    @swits = Swit.order(created_at: :desc)
    @swit = Swit.new

  end

  # GET /swits/1
  # GET /swits/1.json
  def show
  end

  # GET /swits/new
  def new
    @swit = Swit.new
  end
  # show swits of a user
  def profile

  end
  # GET /swits/1/edit
  def edit
  end

  # POST /swits
  # POST /swits.json
  def create
    @swit = Swit.new(swit_params)
    @swit.user_id= current_user.username
    respond_to do |format|
      if @swit.save
        format.html { redirect_to swits_path }
        format.json { render action: 'show', status: :created, location: @swit }
      else
        format.html { render action: 'new' }
        format.json { render json: @swit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swits/1
  # PATCH/PUT /swits/1.json
  def update
    respond_to do |format|
      if @swit.update(swit_params)
        format.html { redirect_to @swit, notice: 'Swit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @swit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swits/1
  # DELETE /swits/1.json
  def destroy
    @swit.destroy
    respond_to do |format|
      format.html { redirect_to swits_url }
      format.json { head :no_content }
    end
  end
   def load_swit
     @swit = Swit.find(params[:swit_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_swit
      @swit = Swit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def swit_params
      params.require(:swit).permit(:post)
    end
end

app/helpers/swits_helper.rb
module SwitsHelper
end

app/views/swits/_form.html.erb
<%= form_for(@swit) do |f| %>
  <% if @swit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@swit.errors.count, "error") %> prohibited this swit from being saved:</h2>

      <ul>
      <% @swit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br>

    <%= f.text_field :post, :placeholder => 'Write a Swit..' %>


  </div>
  <div class="actions">
    <%= f.submit 'Swit', :class => "button right"%>
  </div>
<% end %>

app/views/swits/edit.html.erb
<div id= "sign_up">

<h1>Editing swit</h1>

<%= render 'form' %>

<%= link_to 'Show', @swit %> |
<%= link_to 'Back', swits_path %>
</div>

app/views/swits/index.html.erb
<div id= "my_profile">
<h4>
  <%= current_user.username %>
</h4>

<%= render 'form' %>
<h6>
<%= link_to 'Change Password', edit_user_registration_path %>
</h4>
</div>

<div id= "my_swits" class= "small-12.large-4.columns">
<% @swits.each do |swit| %>
<div>

<br>
<br>
<b><h5>
    <br>
    <%= swit.user_id %></b><br>
    <h6>
    <%= swit.post %>
  
</h4>


<%#=============================== sweet form==========================================================%>

 <% @sweet= Sweet.new%>

<%= form_for([swit, @sweet], :html => {:class => 'sweet_form'}) do |f| %>
  <% if @sweet.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@sweet.errors.count, "error") %> prohibited this sweet from being saved:</h2>

      <ul>
      <% @sweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <input id="sweet_swit_id" name="sweet[swit_id]" type="hidden" value="<%= @swit.id%>" />
 
 
   
     <input name="commit" type="submit" class= "sweet"value="" />

<% end %>



<%#=============================== sweet form==========================================================%>


<%#=============================== sour form==========================================================%>

 <% @sour= Sour.new%>

<%= form_for([swit, @sour], :html => {:class => 'sour_form'}) do |f| %>
  <% if @sour.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@sour.errors.count, "error") %> prohibited this sour from being saved:</h2>

      <ul>
      <% @sour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <input id="sour_swit_id" name="sour[swit_id]" type="hidden" value="<%= @swit.id%>" />
 
 
   
     <input name="commit" type="submit" class= "sour"value="" />

<% end %>



<%#=============================== sweet form==========================================================%>


<%= link_to pluralize(swit.sweets.count.to_s, "Sweet"), swit_sweets_path(swit)  %>
<%= link_to pluralize(swit.sours.count.to_s, "Sour"), swit_sours_path(swit)  %>
<%= link_to pluralize(swit.comments.count.to_s, "Comment"), new_swit_comment_path(swit)  %>


<% if current_user.username ==  swit.user_id  %>
 <%= link_to 'Edit', edit_swit_path(swit) %>
 <%= link_to 'Delete', swit, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<br>


<% @comment= Comment.new
    @swit= swit
%>

<%= render 'comments/form'  %>


</div>
<% end %>
<br>

</div>

app/views/swits/new.html.erb
<h1>New swit</h1>

<%= render 'form' %>

<%= link_to 'Back', swits_path %>

app/views/swits/profile.html.erb
<div id= "my_profile">
<% if current_user.username ==  swit.user_id  %>
<h4>
  <%= current_user.username %>
</h4>

<%= render 'form' %>
<h6>
<%= link_to 'Change Password', edit_user_registration_path %>
</h4>
</div>

<div id= "my_swits" class= "small-12.large-4.columns">
<% @swits.each do |swit| %>
<div>

<br>
<br>
<b><h5>
    <%= swit.user_id %></b><br>
    <h6>
    <%= swit.post %>
  
</h4>


<%#=============================== sweet form==========================================================%>

 <% @sweet= Sweet.new%>

<%= form_for([swit, @sweet], :html => {:class => 'sweet_form'}) do |f| %>
  <% if @sweet.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@sweet.errors.count, "error") %> prohibited this sweet from being saved:</h2>

      <ul>
      <% @sweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <input id="sweet_swit_id" name="sweet[swit_id]" type="hidden" value="<%= @swit.id%>" />
 
 
   
     <input name="commit" type="submit" class= "sweet"value="" />

<% end %>



<%#=============================== sweet form==========================================================%>


<%#=============================== sour form==========================================================%>

 <% @sour= Sour.new%>

<%= form_for([swit, @sour], :html => {:class => 'sour_form'}) do |f| %>
  <% if @sour.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@sour.errors.count, "error") %> prohibited this sour from being saved:</h2>

      <ul>
      <% @sour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <input id="sour_swit_id" name="sour[swit_id]" type="hidden" value="<%= @swit.id%>" />
 
 
   
     <input name="commit" type="submit" class= "sour"value="" />

<% end %>



<%#=============================== sweet form==========================================================%>


<%= link_to pluralize(swit.sweets.count.to_s, "Sweet"), swit_sweets_path(swit)  %>
<%= link_to pluralize(swit.sours.count.to_s, "Sour"), swit_sours_path(swit)  %>
<%= link_to pluralize(swit.comments.count.to_s, "Comment"), new_swit_comment_path(swit)  %>


 <%= link_to 'edit', edit_swit_path(swit) %>
 <%= link_to 'delete', swit, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<br>

<%= render swit.comments %> 
<% @comment= Comment.new
    @swit= swit
%>

<%= render 'comments/form'  %>


</div>
<% end %>
<br>



<% end %>
</div>

app/views/swits/show.html.erb
<div id= "my_profile">

<h4>
  <%= current_user.username %>
</h4>

<%= render 'form' %>
<h6>
<%= link_to 'Change Password', edit_user_registration_path %>
</h4>
</div>

<div id= "my_swits" class= "small-12.large-4.columns">
<% @swits.each do |swit| %>
<div>

<br>
<br>
<% if current_user.username ==  swit.user_id  %>
<b><h5>
    <%= swit.user_id %></b><br>
    <h6>
    <%= swit.post %>
  
</h4>


<%#=============================== sweet form==========================================================%>

 <% @sweet= Sweet.new%>

<%= form_for([swit, @sweet], :html => {:class => 'sweet_form'}) do |f| %>
  <% if @sweet.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@sweet.errors.count, "error") %> prohibited this sweet from being saved:</h2>

      <ul>
      <% @sweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <input id="sweet_swit_id" name="sweet[swit_id]" type="hidden" value="<%= @swit.id%>" />
 
 
   
     <input name="commit" type="submit" class= "sweet"value="" />

<% end %>



<%#=============================== sweet form==========================================================%>


<%#=============================== sour form==========================================================%>

 <% @sour= Sour.new%>

<%= form_for([swit, @sour], :html => {:class => 'sour_form'}) do |f| %>
  <% if @sour.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@sour.errors.count, "error") %> prohibited this sour from being saved:</h2>

      <ul>
      <% @sour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <input id="sour_swit_id" name="sour[swit_id]" type="hidden" value="<%= @swit.id%>" />
 
 
   
     <input name="commit" type="submit" class= "sour"value="" />

<% end %>



<%#=============================== sweet form==========================================================%>


<%= link_to pluralize(swit.sweets.count.to_s, "Sweet"), swit_sweets_path(swit)  %>
<%= link_to pluralize(swit.sours.count.to_s, "Sour"), swit_sours_path(swit)  %>
<%= link_to pluralize(swit.comments.count.to_s, "Comment"), new_swit_comment_path(swit)  %>


 <%= link_to 'edit', edit_swit_path(swit) %>
 <%= link_to 'delete', swit, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<br>

<%= render swit.comments %> 
<% @comment= Comment.new
    @swit= swit
%>

<%= render 'comments/form'  %>


</div>
<% end %>
<br>



<% end %>
</div>