config/routes.rb
Switter2::Application.routes.draw do

 

  

resources :swits do
  resources :comments, :users, :sweets, :sours, :doortags
end
  devise_for :users

root :to => 'swits#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :swit

	validates :body, :presence => true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :load_swit 
	
	def new

    	@comment = @swit.comments.new
    	@comments = @swit.comments.all
    	@swits = Swit.all
	end


 	

  	def index
      @comment = @swit.comments.new
    	@comments = @swit.comments.all
    	
  	end

 
	  def show
	  	@comment = @swit.comments.find(params[:id])

	  end

  
	  def edit

	  	@swit = Swit.find(params[:swit_id])
	  end




	  
	def create
	@comments = @swit.comments.all
	@comment = @swit.comments.new(comments_params)
	@swits = Swit.all
	@comment.user_id= current_user.username
	    respond_to do |format|
	      if @comment.save
	      	
	        format.html { redirect_to swits_path }
	        format.json { render action: 'new', status: :created, location: @comment }
	      else
	        format.html { render action: 'new' }
	        format.json { render json: @swit.errors, status: :unprocessable_entity }
	      end
	    end
	  end

  def load_swit
		 @swit = Swit.find(params[:swit_id])
  end

  def update
  	@swit = Swit.find(params[:swit_id])
    respond_to do |format|
      if @comment.update(comments_params)
       
	    format.html { redirect_to [@swit, @comment]}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comments.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = @swit.comments.find(params[:id])
     @comment.destroy
    respond_to do |format|
      format.html { redirect_to swit_comments_path(@swit) }
      format.json { head :no_content }
    end
  end


  def comments_params
    params.require(:comment).permit(:body, :user_id, :swit_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
%b
  = comment.user_id
%h6
  = comment.body

app/views/comments/_form.html.haml
= form_for([@swit, @comment]) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h4
        = pluralize(@comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_field :body, :placeholder => 'Write a Comment..'
  %input#comment_swit_id{name: "comment[swit_id]", type: "hidden", value: @swit.id}/
  .actions
    = f.submit 'Comment', class: 'button right'

app/views/comments/edit.html.haml
%h1 Editing comment
= render 'form'
= link_to 'Show', @comment
|
\#{link_to 'Back', comments_path}

app/views/comments/index.html.erb
<div>
<h5><%= @swit.user_id %></h5>
<h6><%= @swit.post %></h2>


</div>



    <% @comments.each do |comment| %>
      <div>
       <b> <%= comment.user_id %></b>
        <br>
        <h5><%= comment.body %></h3>
          <%= link_to 'Delete comment', [@swit, comment], confirm: 'Are you sure?', method: :delete %>

      </div>
    
    <% end %>


<%= link_to 'Back', swits_path %>
<br>

app/views/comments/index.html.haml
%h5= @swit.user_id
%h2= @swit.post
- @comments.each do |comment|

%b
  = comment.user_id
%br/
%h3= comment.body
= link_to 'Delete comment', [@swit, comment], confirm: 'Are you sure?', method: :delete
= link_to 'Back', swits_path
%br/

app/views/comments/new.html.haml
#sign_up
  .p
    %h5= @swit.user_id
    %h6= @swit.post
    %b= 'Comments:'
  - @comments.each do |comment|
    - if comment.user_id != nil
      .p
        %h6
        %b
          = comment.user_id
        %h6
          = comment.body
  = render 'form'

  .h7
    = link_to 'Back', swits_path

app/views/comments/show.html.haml
#sign_up
  %p
    %strong Body:
    = @comment.body
  %p
    %strong User:
    = @comment.user_id
  %p
    %strong Swit:
    = @comment.swit_id
  = link_to 'Edit', edit_swit_comment_path(@swit, @comment)
  |
  \#{link_to 'Back', swit_comments_path(@swit)}