config/routes.rb
Switter2::Application.routes.draw do

 

  

resources :swits do
  resources :comments, :users, :sweets, :sours, :doortags
end
  devise_for :users

root :to => 'swits#index'

end

app/models/sour.rb
class Sour < ActiveRecord::Base
belongs_to :swit
end

app/controllers/sours_controller.rb
class SoursController < ApplicationController
  before_action :set_sour, only: [:show, :edit, :update, :destroy]

  before_filter :load_swit 
  # GET /sours
  # GET /sours.json
  def index
    @sours = Sour.all
  end

  # GET /sours/1
  # GET /sours/1.json
  def show
    @sour = @swit.sours.find(params[:id])
  end

  # GET /sours/new
  def new
   @sour = @swit.sours.new
  end

  # GET /sours/1/edit
  def edit

  end

  # POST /sours
  # POST /sours.json
   def create
  @sour = @swit.sours.new(sour_params)
  @swits = Swit.all
  @sour.user_id= current_user.username
      respond_to do |format|
        if @sour.save
          
          format.html { redirect_to swits_path }
          format.json { render action: 'new', status: :created, location: @sour }
        else
          format.html { render action: 'new' }
          format.json { render json: @swit.errors, status: :unprocessable_entity }
        end
      end
  
    end

  # PATCH/PUT /sours/1
  # PATCH/PUT /sours/1.json
  def update
    respond_to do |format|
      if @sour.update(sour_params)
       format.html { redirect_to swits_path, notice: 'sour <3.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sours/1
  # DELETE /sours/1.json
  def destroy
    @sour = @swit.sours.find(params[:id])
     @sour.destroy
    respond_to do |format|
      format.html { redirect_to swit_sours_path(@swit) }
      format.json { head :no_content }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sour
      #@sour =  @swits.sour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sour_params
       params.require(:sour).permit(:user_id, :swit_id)
    end

     def load_swit
     @swit = Swit.find(params[:swit_id])
  end
end

app/helpers/sours_helper.rb
module SoursHelper
end

app/views/sours/_form.html.erb
<%= form_for([@swit, @sour]) do |f| %>
  <% if @sour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sour.errors.count, "error") %> prohibited this sour from being saved:</h2>

      <ul>
      <% @sour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <input id="sour_swit_id" name="sour[swit_id]" type="hidden" value="<%= @swit.id%>" />
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sours/edit.html.erb
<div id= "sign_up">
<h1>Editing sour</h1>

<%= render 'form' %>

<%= link_to 'Show', @sour %> |
<%= link_to 'Back', sours_path %>
</div>

app/views/sours/index.html.erb
<div id= "sign_up">
<h1>Listing sours</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Swit</th>
    </tr>
  </thead>

  <tbody>
    <% @sours.each do |sour| %>
      <tr>
        <td><%= sour.user_id %></td>
        <td><%= sour.swit_id %></td>
        
        <td> <%= link_to 'Delete sour', [@swit, sour], confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <h7>
   <%= link_to 'Back', swits_path %>
</div>

app/views/sours/new.html.erb
<div id= "sign_up">
<h1>New sour</h1>

<%= render 'form' %>

<%= link_to 'Back', sours_path %>
</div>

app/views/sours/show.html.erb
<div id= "sign_up">

<p>
  <strong>User:</strong>
  <%= @sour.user_id %>
</p>

<p>
  <strong>Swit:</strong>
  <%= @sour.swit_id %>
</p>

<%= link_to 'Edit', edit_swit_sour_path(@swit, @sour) %> |
<%= link_to 'Back', swit_sours_path(@swit) %>

</div>